#define SERVO_PIN 5
#define ESC_PIN 4
#define ON_BOARD_LED_PIN 16
#define HEAD_LED_PIN 15
#define RIGHT_LED_PIN 14
#define LEFT_LED_PIN  12
#define REVERSE_LED_PIN 13
#define PWM_MID 1500
#define FAIL_SAFE_VALUE 1500
#define CRSF_STEERING_CHANNEL 4
#define CRSF_ESC_CHANNEL 2
#define CRSF_HEAD_LIGHT_CHANNEL 6
#define CRSF_HAZARD_LIGHT_CHANNEL 7

#define DEAD_BAND  300
#define NUM_SERVOS 2

const unsigned long BLINK_INTERVAL_MS = 800;
