#define SERVO_PIN 12
#define ESC_PIN 13
#define HEAD_LED_PIN 4
#define LEFT_STEERING_LED_PIN 5
#define RIGHT_STEERING_LED_PIN 14
#define REVERSE_LED_PIN 15
const unsigned long BLINK_INTERVAL_MS = 800;
